---
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /portainer/Files/AppData/Config/Heimdall:/config
    ports:
      - 32770:80
      - 32771:443
    restart: unless-stopped
