---
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    network_mode: host
    environment:
      - PRIMARY=http://172.20.10.20|<API_PASSWORD>
      - REPLICAS=http://172.20.10.202:88|<API_PASSWORD>,http://172.20.10.203:88|<API_PASSWORD>
      - RUN_GRAVITY=false
      - FULL_SYNC=true
      - CRON=*/10 * * * *
