version: "3"
services:
  gluetun:
    container_name: home-gluetun
    image: qmcgaw/gluetun
    networks:
      home_lab_extension:
        ipv4_address: 192.168.19.2
    cap_add:
      - NET_ADMIN
    privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - DOT=off # To allow Gluetun to respond to DNS queries from LAN
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_ENDPOINT_IP=<HOME PUBLIC IP>
      - WIREGUARD_ENDPOINT_PORT=51820
      - WIREGUARD_PUBLIC_KEY=<PUB KEY>
      - WIREGUARD_PRIVATE_KEY=<PRIVATE KEY>
      - WIREGUARD_PRESHARED_KEY=<PSK>
      - WIREGUARD_ADDRESSES=10.1.1.2/32
      - BLOCK_MALICIOUS=false
    volumes:
        - /iptables:/iptables

networks:
  home_lab_extension:
    external: true
    name: home_lab_extension
